# 应用名称
spring:
  application:
    name: -1shop
    # spring 静态资源扫描路径
  resources:
    static_locations: classpath:/static/
  profiles:
    active: dev


secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin-info/login
      - /admin/register
      - /admin/info
      - /admin/logout

#mybatis
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ssh.shop.entity
  mapper-locations: classpath:/mapper/**Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #    capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxxroor
    #自定义SQL注入器





